name: CI

# 当对同一个 PR 有新提交时，自动取消正在进行的旧构建
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
  pull_request:
  # 允许从 GitHub Actions 页面手动触发此工作流
  workflow_dispatch:
    inputs:
      publish_to_pypi:
        description: '是否发布到 PyPI? (仅在手动触发时有效)'
        required: false
        type: boolean
        default: false

jobs:
  build-linux:
    name: Build wheels on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build wheels
      uses: messense/maturin-action@v1
      with:
        manylinux: "2014"
        command: build
        args: --release -o dist
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-linux
        path: dist

  build-windows:
    name: Build wheels on Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build wheels
      uses: messense/maturin-action@v1
      with:
        command: build
        args: --release --no-sdist -o dist
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-windows
        path: dist

  build-macos:
    name: Build wheels on macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build wheels
      uses: messense/maturin-action@v1
      with:
        command: build
        args: --release --no-sdist -o dist --universal2
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-macos
        path: dist

  release:
    name: Release to PyPI
    runs-on: ubuntu-latest
    # 仅在推送 tag 或手动触发并选择发布时运行
    if: "startsWith(github.ref, 'refs/tags/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.publish_to_pypi == 'true')"
    needs: [ build-macos, build-windows, build-linux ]
    # 添加发布到 PyPI 所需的权限
    permissions:
      id-token: write
    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          # 将所有工件下载到 dist 目录
          path: dist
          # 匹配所有以 wheels- 开头的工件
          pattern: wheels-*
          # 将所有工件内容合并到 path 指定的单个目录中
          merge-multiple: true

      - name: Publish to PyPI
        uses: messense/maturin-action@v1
        with:
          command: upload
          # --skip-existing: 如果版本已存在则跳过
          # dist/*: 上传 dist 目录下的所有文件
          args: --skip-existing dist/*